# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cube <- function(x) {
    .Call('_my2stpkg_cube', PACKAGE = 'my2stpkg', x)
}

